language: python
python:
 - "3.8"
before_install:
 - sudo apt-get update
 - sudo apt-get install poppler-utils
 - sudo apt-get install libxml2-dev libxslt1-dev
 - sudo apt-get install openjdk-8-jdk icedtea-8-plugin
 - sudo apt-get install maven
 - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
install:
 - pip install --upgrade setuptools
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
services:
 - rabbitmq
before_script:
 - mvn package
script:
 - py.test
 #- tests/integration_test.sh
 #- mvn test -DdryRun=true -DcoverallsFile=java_coverage.json jacoco:report coveralls:report
after_success:
 - coverage combine
 - coveralls #--merge=java_coverage.json
