language: python
python:
 - "2.7"
before_install:
 - sudo apt-get update
 - sudo apt-get install openjdk-7-jdk icedtea-7-plugin libxml2-dev libxslt1-dev
 - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
install:
 - pip install --upgrade setuptools
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
services:
 - rabbitmq
before_script:
 - sudo rabbitmqctl add_vhost adsfulltext
 - sudo rabbitmqctl add_vhost external_vhost
 - sudo rabbitmqctl set_permissions -p adsfulltext guest ".*" ".*" ".*"
 - sudo rabbitmqctl set_permissions -p external_vhost guest ".*" ".*" ".*"
 - mvn package
script:
 - py.test
 #- tests/integration_test.sh
 - mvn test -DdryRun=true -DcoverallsFile=java_coverage.json jacoco:report coveralls:report
after_success:
 - coverage combine
 - coveralls --merge=java_coverage.json
