name: GitHub Actions CI

on: [pull_request]
env:
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

#    - uses: nijel/rabbitmq-action@v1.0.0
#      with:
#        rabbitmq version: '5'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install poppler-utils
        sudo apt-get install libxml2-dev libxslt1-dev
        sudo apt-get install openjdk-8-jdk icedtea-8-plugin
        sudo apt-get install maven
        
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade wheel setuptools pip
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt
          
    - name: Run Maven
      run: |
        mvn package
        
    - name: Test with pytest
      run: |
        py.test

#    - name: Combine coverage
#      run: |
#        coverage combine

    - name: Upload coverage data to coveralls.io
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
